### ISSUE TITLE
Server appears to be down

### ISSUE THREAD

**Issue by jnieuwdorp** [rmhartog/octopull#18]
The octopull loader keeps displaying the loading animation and the error "Failed to load resource: net::ERR_CONNECTION_TIMED_OUT" keeps stacking. https://octopull.rmhartog.me/  also times out.

**Comment by rmhartog** [comment]
Hello @jnieuwdorp, thanks for letting me know. It seems the server was shut down accidentally. Could you please check if the service has been restored for you?

**Comment by jnieuwdorp** [comment]
Yes, It's back up again
