### ISSUE TITLE
Login fails

### ISSUE THREAD

**Issue by rutgervandenberg** [rmhartog/octopull#2]
Whenever I open a pull request a yellow bar shows up where octopull asks me to log in. When I click it the first time, I'm asked to allow octopull to access my github account. When I accept this, I am returned to the original page and the yellow bar shows up again telling me I'm not logged in. Pressing the log in button after the first time only seems to refresh the page.

**Comment by rmhartog** [comment]
Thanks for reporting the problem, I'm looking into it. Could you try the following to help me pinpoint the problem?
- Go to a pull-request in Chrome where it displays the yellow bar
- Open Chrome DevTools by pressing F12
- Switch to the Network tab
- Check the `Disable Cache` box
- While keeping the DevTools tab open, click `Log in` again

**Comment by rutgervandenberg** [comment]
The problem persists with cache disabled.  Shows a large number of (attempted) connections, including a 403 from octopull.js:9603. Is there anything specific you're looking for?

I also tried this on two machines and operating systems (Linux mint and Windows 8.1), with both showing the same problem.

**Comment by rmhartog** [comment]
I'm not sure if this is relevant, but what version of Chrome are you running?

Here is what I expect to happen:
- `octopull.js` receives the 403 Forbidden error from the server and displays the warning
- The user goes to the `/oauth/login/` page by clicking the link
- The user is redirected to GitHub for authentication
- GitHub redirects back to `/oauth/authorize/` with some parameters
- The user is redirected to the pull-request with a cookie `github_token`
- `octopull.js` retries the request with this cookie and succeeds

Do you think you could verify this behaviour with the DevTools network tab, or do you need more elaborate instructions? Let me know. In any case, make sure that you **do not** post the exact value of the authentication parameters or the value of your `github_token` cookie.

**Comment by rutgervandenberg** [comment]
The issue seems to be resolved. 
When you mentioned cookies I recalled that i've got third party cookies blocked so I added an exception and tried logging in again. This didn't really change much. After this I cleared all my cookies and tried again. Login works now.

Removing the exception shows the same problem again, so it seems that it is the cause.

**Comment by rmhartog** [comment]
Glad to hear that it is resolved. Bugs like this are sometimes hard to track down.
Please note that there is currently another issue where reports from Travis don't come in properly, so you will not be able to see warnings just yet. I'm working hard to resolve it.

Cheers!
